import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {setupClubMail} from '../club-mail.mjs';
class InputError extends Error{}
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;CREATE TABLE league_entries(id TEXT PRIMARY KEY);');const clubs=['Prairie Sky FC','Youth Football Club'];const env={};let requests=[];let fail=false;const mail=setupClubMail({db,clubs,InputError,email:value=>value,env,startWorker:false,send:async(url,options)=>{requests.push({url,...options});if(fail)throw Error('connection failed');return{ok:true,json:async()=>({id:'provider-test-id'})}}});function add(id){db.prepare('INSERT INTO league_entries VALUES(?)').run(id);mail.enqueue({id,firstName:'Test',lastName:'Child',birthYear:2016,team:{club:'Prairie Sky FC',name:'Prairie Sky FC U10'},account:{name:'Test Parent',email:'parent@example.test'},contactPhone:'+1 204 555 0123',consent:{media:false,interviews:false,publicStats:false},signedAt:new Date().toISOString()})}return{db,env,mail,requests,add,setFail:value=>fail=value}}
test('queues without credentials; sends only selected club with parent Reply-To and idempotency; accepted messages never resend',async()=>{const f=fixture();try{f.add('entry-a');await f.mail.flush();assert.equal(f.requests.length,0);assert.equal(f.mail.forEntry('entry-a').status,'queued');f.env.RESEND_API_KEY='test-only-key';f.env.CLUB_MAIL_FROM='SJL <registrations@example.test>';await f.mail.flush();assert.equal(f.requests.length,1);const request=f.requests[0],payload=JSON.parse(request.body);assert.equal(request.url,'https://api.resend.com/emails');assert.deepEqual(payload.to,['info@prairieskyfc.ca']);assert.equal(payload.reply_to,'parent@example.test');assert.match(payload.text,/Test Child/);assert.match(payload.text,/Parent phone: \+1 204/);assert.match(payload.text,/Photos \/ video: NO/);assert.doesNotMatch(payload.text,/password|recoveryCode|policyHash/i);assert.ok(request.headers['Idempotency-Key']);assert.equal(f.mail.forEntry('entry-a').status,'accepted');await f.mail.flush();assert.equal(f.requests.length,1);assert.throws(()=>f.mail.retry(f.mail.forEntry('entry-a').id));}finally{f.db.close()}});
test('failed email leaves registration intact; retries reuse key and do not resend after idempotency window',async()=>{const f=fixture();try{f.env.RESEND_API_KEY='test';f.env.CLUB_MAIL_FROM='SJL <registrations@example.test>';f.add('entry-a');f.setFail(true);await f.mail.flush();assert.equal(f.mail.forEntry('entry-a').status,'failed');assert.ok(f.db.prepare('SELECT id FROM league_entries').get());f.setFail(false);f.mail.retry(f.mail.forEntry('entry-a').id);await f.mail.flush();assert.equal(f.requests[0].headers['Idempotency-Key'],f.requests[1].headers['Idempotency-Key']);assert.equal(f.mail.forEntry('entry-a').status,'accepted');f.add('entry-b');f.db.prepare('UPDATE league_mail_outbox SET firstAttempt=? WHERE entryId=?').run(Date.now()-24*60*60*1000,'entry-b');await f.mail.flush();assert.equal(f.mail.forEntry('entry-b').status,'needs_review');assert.equal(f.requests.length,2)}finally{f.db.close()}});
test('admin contact updates affect only unsent notifications and survive module initialization',async()=>{const f=fixture();try{f.add('entry-a');f.mail.updateContact('Prairie Sky FC','updated@example.test');assert.equal(f.mail.forEntry('entry-a').recipient,'updated@example.test');const m=setupClubMail({db:f.db,clubs:['Prairie Sky FC'],InputError,email:value=>value,env:f.env,startWorker:false});assert.equal(m.overview().contacts.find(c=>c.club==='Prairie Sky FC').email,'updated@example.test');assert.throws(()=>f.mail.updateContact('unknown','test@example.test'))}finally{f.db.close()}});
