import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
let dir,child,base,admin,parentA,parentB,entryId,recovery,statsId,team,policyVersion;
const adminPassword=randomBytes(24).toString('hex'),parentPassword=randomBytes(16).toString('hex');
async function start(){child=spawn(process.execPath,['server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,DATA_DIR:dir,ADMIN_PASSWORD:adminPassword,PORT:'0',NODE_ENV:'test'},stdio:['ignore','pipe','pipe']});let output='',errors='';child.stderr.on('data',b=>errors+=b);await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error(errors)),5000);child.stdout.on('data',b=>{output+=b;const match=output.match(/port (\d+)/);if(match){base='http://127.0.0.1:'+match[1];clearTimeout(timer);resolve()}})})}
async function stop(){child.kill('SIGTERM');await once(child,'exit')}
async function api(path,method='GET',payload,cookie,headers={}){const response=await fetch(base+path,{method,headers:{...(payload?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{}),...headers},body:payload?JSON.stringify(payload):undefined});return{response,data:await response.json()}}
function extractCookie(r){assert.match(r.headers.get('set-cookie'),/HttpOnly/);return r.headers.get('set-cookie').split(';')[0]}
const entry=()=>({firstName:'Test',lastName:'Junior',birthYear:2016,teamId:team.id,policyVersion,rules:true,discipline:true,acknowledgement:true,guardian:true,signedBy:'Test Guardian',contactPhone:'+1 204 555 0123',clubContactConsent:true,media:false,interviews:false,publicStats:false});
before(async()=>{dir=await mkdtemp(join(tmpdir(),'sjl-league-'));await start();const data=(await api('/api/league/teams')).data;team=data.teams.find(t=>t.club==='Prairie Sky FC'&&t.ageGroup==='U10');policyVersion=data.policyVersion;admin=extractCookie((await api('/api/admin/login','POST',{password:adminPassword})).response)});
after(async()=>{await stop();await rm(dir,{recursive:true,force:true})});
test('serves both portal pages and versioned English documents with actual scheduled teams',async()=>{for(const path of ['/parent','/registration-player','/registration-player/','/league-register'])assert.equal((await fetch(base+path)).status,200);const policies=await(await fetch(base+'/assets/league-policies.json')).json();assert.equal(policies.documents.length,4);assert.equal(policies.documents[0].sections.length,24);assert.equal(policies.version,policyVersion);assert.equal((await api('/api/league/teams')).data.teams.length,8);assert.equal((await fetch(base+'/league.mjs')).status,404)});
test('creates parent accounts with hashed passwords, isolated sessions and recovery codes',async()=>{let r=await api('/api/parent/signup','POST',{email:'guardian-a@example.test',password:parentPassword,name:'Test Guardian',guardian:true});assert.equal(r.response.status,201);parentA=extractCookie(r.response);recovery=r.data.recoveryCode;assert.match(recovery,/^[a-f0-9]{48}$/);assert.equal(r.data.account.passwordHash,undefined);r=await api('/api/parent/signup','POST',{email:'guardian-b@example.test',password:parentPassword,name:'Other Guardian',guardian:true});parentB=extractCookie(r.response);assert.equal((await api('/api/admin/players','GET',undefined,parentA)).response.status,401);assert.equal((await api('/api/parent/players','GET',undefined,admin)).response.status,401);assert.equal((await api('/api/parent/login','POST',{email:'guardian-a@example.test',password:'incorrect-long-password'})).response.status,401);assert.equal((await api('/api/parent/signup','POST',{email:'guardian-a@example.test',password:parentPassword,name:'Duplicate',guardian:true})).response.status,409)});
test('requires document acceptance and team validity; protects private registrations',async()=>{assert.equal((await api('/api/parent/players','POST',entry())).response.status,401);assert.equal((await api('/api/parent/players','POST',{...entry(),rules:false},parentA)).response.status,400);assert.equal((await api('/api/parent/players','POST',{...entry(),policyVersion:'old'},parentA)).response.status,409);assert.equal((await api('/api/parent/players','POST',{...entry(),teamId:'invented'},parentA)).response.status,400);assert.equal((await api('/api/parent/players','POST',entry(),parentA,{Origin:'https://evil.test'})).response.status,403);assert.equal((await api('/api/parent/players','POST',{...entry(),contactPhone:''},parentA)).response.status,400);assert.equal((await api('/api/parent/players','POST',{...entry(),clubContactConsent:false},parentA)).response.status,400);const r=await api('/api/parent/players','POST',entry(),parentA);assert.equal(r.response.status,201);entryId=r.data.player.id;assert.equal(r.data.player.status,'pending');assert.equal(r.data.player.stats,null);assert.ok(r.data.player.schedule.matches.length>0);for(const m of r.data.player.schedule.matches){assert.equal(m.ageGroup,'U10');assert.ok(m.home==='Prairie Sky FC'||m.away==='Prairie Sky FC')}assert.equal(r.data.player.contactPhone,'+1 204 555 0123');assert.equal(r.data.player.consent.rules,true);assert.equal((await api('/api/parent/players','POST',entry(),parentA)).response.status,409);assert.equal((await api('/api/parent/players','GET',undefined,parentB)).data.players.length,0);assert.equal((await api('/api/parent/players/'+entryId+'/consent','PUT',{media:true,interviews:true,publicStats:true,policyVersion},parentB)).response.status,404);assert.equal((await api('/api/stats')).data.players.length,0)});
test('admin explicitly verifies/link existing totals; parent and public statistics share the same record',async()=>{const p={name:'Test Junior',club:team.club,ageGroup:team.ageGroup,goals:5,assists:2,cleanSheets:1};const r=await api('/api/admin/players','POST',p,admin);statsId=r.data.player.id;assert.equal((await api('/api/admin/league-entries/'+entryId+'/review','POST',{verified:true,status:'approved'},parentA)).response.status,401);assert.equal((await api('/api/admin/league-entries/'+entryId+'/review','POST',{verified:true,status:'approved'},admin)).response.status,409);assert.equal((await api('/api/admin/league-entries/'+entryId+'/review','POST',{verified:true,status:'approved',statsPlayerId:statsId,note:'Roster checked'},admin)).response.status,200);let profile=(await api('/api/parent/players','GET',undefined,parentA)).data.players[0];assert.equal(profile.stats.goals,5);assert.equal(profile.stats.assists,2);assert.equal((await api('/api/stats')).data.players.length,0);assert.equal((await api('/api/admin/players/'+statsId,'PUT',{...p,version:1,name:'Changed identity'},admin)).response.status,409);assert.equal((await api('/api/admin/players/'+statsId,'PUT',{...p,version:1,goals:9},admin)).response.status,200);profile=(await api('/api/parent/players','GET',undefined,parentA)).data.players[0];assert.equal(profile.stats.goals,9);assert.equal((await api('/api/parent/players/'+entryId+'/consent','PUT',{media:true,interviews:false,publicStats:true,policyVersion},parentA)).response.status,200);assert.equal((await api('/api/stats')).data.players[0].goals,9);assert.doesNotMatch(JSON.stringify((await api('/api/stats')).data),/guardian-a|birthYear|signedBy|parentId/);assert.equal((await api('/api/parent/players/'+entryId+'/consent','PUT',{media:false,interviews:false,publicStats:false,policyVersion},parentA)).response.status,200);assert.equal((await api('/api/stats')).data.players.length,0);const roster=(await api('/api/admin/league-entries','GET',undefined,admin)).data.entries[0];assert.equal(roster.notification.status,'queued');assert.equal(roster.notification.recipient,'info@prairieskyfc.ca');assert.equal(roster.parentNotification.recipient,'guardian-a@example.test');assert.equal(roster.parentNotification.status,'queued');assert.equal((await api('/api/admin/league-mail','GET',undefined,parentA)).response.status,401);assert.equal((await api('/api/admin/league-mail','GET',undefined,admin)).data.configured,false);const history=(await api('/api/admin/league-entries','GET',undefined,admin)).data.entries[0].consentHistory;assert.equal(history.length,3);assert.equal(history[0].consent.publicStats,false);assert.equal(history[1].consent.publicStats,true)});
test('supports siblings, safe duplicate identity review and configurable team additions',async()=>{const r=await api('/api/parent/players','POST',{...entry(),firstName:'Sibling'},parentA);assert.equal(r.response.status,201);assert.equal((await api('/api/admin/league-entries/'+r.data.player.id+'/review','POST',{verified:true,status:'approved',statsPlayerId:statsId},admin)).response.status,400);assert.equal((await api('/api/admin/league-entries/'+r.data.player.id+'/review','POST',{verified:true,status:'approved'},admin)).response.status,200);assert.equal((await api('/api/parent/players','GET',undefined,parentA)).data.players.length,2);assert.equal((await api('/api/admin/league-teams','POST',{name:'YFC U10',club:'Youth Football Club',ageGroup:'U10'},admin)).response.status,201);assert.equal((await api('/api/league/teams')).data.teams.length,9)});
test('parent sessions, profiles and permission history survive restart; recovery rotates code and invalidates sessions',async()=>{await stop();await start();assert.equal((await api('/api/parent/players','GET',undefined,parentA)).data.players.length,2);assert.equal((await api('/api/admin/session','GET',undefined,admin)).response.status,401);assert.equal((await api('/api/parent/recover','POST',{email:'guardian-a@example.test',password:parentPassword,recoveryCode:'incorrect-code'})).response.status,401);const r=await api('/api/parent/recover','POST',{email:'guardian-a@example.test',password:parentPassword,recoveryCode:recovery});assert.equal(r.response.status,200);assert.notEqual(r.data.recoveryCode,recovery);assert.equal((await api('/api/parent/players','GET',undefined,parentA)).response.status,401);assert.equal((await api('/api/parent/recover','POST',{email:'guardian-a@example.test',password:parentPassword,recoveryCode:recovery})).response.status,401);parentA=extractCookie(r.response);assert.equal((await api('/api/parent/players','GET',undefined,parentA)).data.players[0].stats.goals,0);assert.equal((await api('/api/parent/logout','POST',{},parentA)).response.status,200);assert.equal((await api('/api/parent/session','GET',undefined,parentA)).response.status,401)});
